### ISSUE TITLE
API was removed in 2.0.0?

### ISSUE THREAD

**Issue by joeframbach** [classcraft/cytoscape.js-canvas#2]
What are the plans for the future of cytoscape-canvas? It looks like the API was removed in https://github.com/classcraft/cytoscape.js-canvas/commit/b4049829948de42d9e91e74026248bccb7622675#diff-e87e7733693f3468c9750b957e64b300L54, so it is entirely non-backwards-compatible. Will the API be replaced with something new?

**Comment by anault** [comment]
The API was removed because the assumption of a CanvasRenderingContext2D makes the canvas unusable for WebGL. 

I could work on an option to specify `Context2D` or `WebGL` (default to `Context2D`) so we can have that API back.

Thoughts?

**Comment by joeframbach** [comment]
I see, that makes sense. I would prefer it to be done in a way that is a non-breaking change. Such as, create an option `renderingEngine` which defaults to `Context2D` which the user may set to `WebGL` if they choose. It would be a transparent change for users upgrading. Thanks for responding so quickly!

**Comment by anault** [comment]
> Create an option `renderingEngine` which defaults to `Context2D` which the user may set to `WebGL`

That's exactly what I meant 😄  I'll see what I can do.

**Comment by anault** [comment]
Restored in [3.0.0](https://github.com/classcraft/cytoscape.js-canvas/releases/tag/3.0.0) (https://github.com/classcraft/cytoscape.js-canvas/commit/016f6873124b1f00a203983e783b137b8d1c5d0b) but no assumption of rendering engine is made. The user can pick whichever he chooses via `canvas.getContext(/*engine*/)`.

`clear`, `resetTransform` & `setTransform` helpers are available if `CanvasRenderingContext2D` is used. These helpers now required a `CanvasRenderingContext2D` to be passed as argument.
