### ISSUE TITLE
Readme: Over / under

### ISSUE THREAD

**Issue by maxkfranz** [classcraft/cytoscape.js-canvas#3]
It might be good to mention in the readme that this extension can be used to place a canvas under or over Cytoscape.  The intro sentence makes it sound like it's just for the under case, until you see later that you can set the z-index.

**Comment by maxkfranz** [comment]
Whoops.  Didn't see it right.  Not enough coffee...

**Comment by JoeFurfaro** [comment]
How can I make the image show up under my cytoscape graph? Lowering the z-index to `-1` made my image not visible, and as soon as it is set to `0` it layers over my nodes.

Sorry to comment so long after this issue was opened! @maxkfranz
