### ISSUE TITLE
cytoscape and canvas misalign when devicePixelRatio is not equal to one

### ISSUE THREAD

**Issue by wrnrlr** [classcraft/cytoscape.js-canvas#8]
I've recently noticed some confusing behaviour when using the canvas extension to draw a shape behind an element. When the page is loaded while the devicePixelRatio of the window is not equal to one the element and associated shape are "out of line".

I notice this on normal displays with chrome and firefox when the resolution is increased by pressing "CMD =" (before the page is loaded) and on retina displays with chrome, firefox and safari.
If the resolution is decreased on a retina display by pressing "CMD -" until devicePixelRatio equals one the element and share can be made to line up on chrome and firefox (after reloading the page).
Safari does not change the devicePixelRatio when zooming the browser window instead it only shows the expected result when the devicePixelRatio is equal to one.

From what I could gather from the code the canvas extension does take the value of devicePixelRatio into account when calculating the dimensions of the canvas element.

How should I handle this issue? @maxkfranz @anault 

For your connivance I've created a demo based off this repo for you to try out:
https://github.com/wrnrlr/debug-canvas
Just clone and open the demo

**Comment by maxkfranz** [comment]
The extension resizes the canvas but -- at first glance -- it does not seem to redraw afterwards.

https://github.com/classcraft/cytoscape.js-canvas/blob/3.0.1/src/cytoscape-canvas.js#L28

**Comment by maxkfranz** [comment]
It's probably your responsibility to redraw the scene on resize.  I don't think the extension would keep track of all the operations and replay them.

**Comment by wrnrlr** [comment]
I figured it out, the problem was with my code I should have used node.boundingBox instead of renderedBoundingBox and call setTransform after ctx.clear().

This snipped does the job as expected:

```
cy.on("render cyCanvas.resize", (evt) => {
    bottomLayer.resetTransform(ctx);
    bottomLayer.clear(ctx);
    bottomLayer.setTransform(ctx);
    ctx.fillStyle = '#e0e0e0'
    cy.nodes().forEach(node => {
        let pos = node.position()
        console.log(pos)
        let box = node.boundingBox({
            includeNodes: true,
            includeEdges: true,
            includeLabels: false,
            includeOverlays: false
        })
        console.log(box)
        ctx.fillRect(box.x1 - box.w / 4, box.y1 - box.h / 4, box.w * 1.5, box.h * 1.5)
    })
});
```

Thanks for your time.
